// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCozpwyGrY3EwjJnUaVA1hAE0bFucblM3A',
    appId: '1:811936977284:web:5af2c4c3bab3c3154f4dd1',
    messagingSenderId: '811936977284',
    projectId: 'bananabaypirates',
    authDomain: 'bananabaypirates.firebaseapp.com',
    databaseURL: 'https://bananabaypirates-default-rtdb.firebaseio.com',
    storageBucket: 'bananabaypirates.firebasestorage.app',
    measurementId: 'G-NMSW10SEFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1Z3K7M-NHQLKQIEE9iZ6Zd9busjQZST0',
    appId: '1:811936977284:android:e4398b22b7438b224f4dd1',
    messagingSenderId: '811936977284',
    projectId: 'bananabaypirates',
    databaseURL: 'https://bananabaypirates-default-rtdb.firebaseio.com',
    storageBucket: 'bananabaypirates.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBshl6e2mJGwZzI5WT3yllz0Kof8fKHk1Q',
    appId: '1:811936977284:ios:9c1625a2ad7083f94f4dd1',
    messagingSenderId: '811936977284',
    projectId: 'bananabaypirates',
    databaseURL: 'https://bananabaypirates-default-rtdb.firebaseio.com',
    storageBucket: 'bananabaypirates.firebasestorage.app',
    iosBundleId: 'com.rebeccals.bbPirates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBshl6e2mJGwZzI5WT3yllz0Kof8fKHk1Q',
    appId: '1:811936977284:ios:9c1625a2ad7083f94f4dd1',
    messagingSenderId: '811936977284',
    projectId: 'bananabaypirates',
    databaseURL: 'https://bananabaypirates-default-rtdb.firebaseio.com',
    storageBucket: 'bananabaypirates.firebasestorage.app',
    iosBundleId: 'com.rebeccals.bbPirates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCozpwyGrY3EwjJnUaVA1hAE0bFucblM3A',
    appId: '1:811936977284:web:a2d0ffbe3d25d31c4f4dd1',
    messagingSenderId: '811936977284',
    projectId: 'bananabaypirates',
    authDomain: 'bananabaypirates.firebaseapp.com',
    databaseURL: 'https://bananabaypirates-default-rtdb.firebaseio.com',
    storageBucket: 'bananabaypirates.firebasestorage.app',
    measurementId: 'G-DM096WE228',
  );
}
